import { ThemeProvider } from '@/components/theme-provider'
import type { Metadata } from 'next'
import { NextIntlClientProvider } from 'next-intl'
import { getMessages } from 'next-intl/server'
import { Geist, Geist_Mono, Montserrat, Roboto } from 'next/font/google'
import NextTopLoader from 'nextjs-toploader'
import './globals.css'

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
})

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
})

const fontRoboto = Roboto({
	weight: ['300', '400', '700', '900'],
	subsets: ['latin'],
	variable: '--font-roboto',
})

const fontMonseratti = Montserrat({
	weight: ['400', '700'],
	subsets: ['latin'],
	variable: '--font-monseratti',
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default async function RootLayout({
	children,
	params,
}: Readonly<{
	children: React.ReactNode
	params: Promise<{ lng: string }>
}>) {
	const { lng } = await params
	const messages = await getMessages({ locale: lng })

	return (
		<html lang={lng} suppressHydrationWarning>
			<body
				className={`${geistSans.variable} ${geistMono.variable} ${fontRoboto.variable} ${fontMonseratti.variable} antialiased`}
			>
				<NextIntlClientProvider messages={messages} locale={lng}>
					<NextTopLoader
						color='#016461'
						height={5}
						showSpinner={false}
						speed={200}
					/>
					<ThemeProvider
						attribute='class'
						defaultTheme='system'
						enableSystem
						disableTransitionOnChange
					>
						{children}
					</ThemeProvider>
				</NextIntlClientProvider>
			</body>
		</html>
	)
}
